local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("markdown", {
	s("monster", {
		t({ "## " }),
		i(2, "Monster Name"),
		t({ "(" }),
		i(3, "Quantity"),
		t({ ")", "" }),
		t({ "### Stats", "- **AC:** " }),
		i(4, "AC"),
		t({ "", "- **HP:** " }),
		i(5, "HP"),
		t({ "", "- **Saves:** Fort +" }),
		i(6, "X"),
		t({ ", Ref +" }),
		i(7, "X"),
		t({ ", Will +" }),
		i(8, "X"),
		t({ "", "- **Speed:** " }),
		i(9, "Speed"),
		t({ "", "- **Immunities:** " }),
		i(10, "Immunities"),
		t({ "", "- **Resistances:** " }),
		i(11, "Resistances"),
		t({ "", "- **Weaknesses:** " }),
		i(12, "Weaknesses"),
		t({ "", "", "### Attacks", "- **" }),
		i(13, "Attack Name"),
		t({ ": +" }),
		i(14, "Attack Bonus"),
		t({ "", "  - **Damage:** " }),
		i(15, "XdY Type"),
		t({ "", "  - **Special:** " }),
		i(16, "Special Effects"),
		t({ "", "", "### Abilities / Traits" }),
		t({ "", "- **" }),
		i(17, "Ability 1"),
		t({ ": " }),
		i(18, "Description"),
		t({ "", "- **" }),
		i(19, "Ability 2"),
		t({ ": " }),
		i(20, "Description"),
		t({ "", "", "### Notes / Tactics", "" }),
		i(21, "Notes or strategy"),
	}),

    s("enemy", {
        t("### ["), i(1, "Enemy Name"), t("]("), i(2, "https://link.here"), t(") ("), i(3, "1"), t({")", ""}),
        t({"", "**Stats:**"}),
        t({"", "- AC: "}), i(4, "00"),
        t({"", "- HP: "}), i(5, "00"),
        t({"", "- Saves: Fort +"}), i(6, "0"), t(", Ref +"), i(7, "0"), t(", Will +"), i(8, "0"),
        t({"", "- Speed: "}), i(9, "00"),

        t({"", "", "**Attacks:**"}),
        t({"", "- **"}), i(10, "Attack Name"), t(":** +"), i(11, "0"), t(", Damage: "), i(12, "xd6+X"), t(" "), i(13, "Slashing"),
        t({"", "- **"}), i(10, "Attack Name"), t(":** +"), i(11, "0"), t(", Damage: "), i(12, "xd6+X"), t(" "), i(13, "Slashing"),

        t({"", ""}),
    }),

	s("combat", {
		t({
			"| Name             | Init | HP    | Statuses            | Notes             |",
			"|-----------------|------|-------|--------------------|-----------------|",
			"| ",
		}),
		i(1, "Name"),
		t(" | "),
		i(2, "Init"),
		t(" | "),
		i(3, "Current/Max HP"),
		t(" | "),
		i(4, "Statuses"),
		t(" | "),
		i(5, "Notes"),
		t(" |"),
		t({ "", "| " }),
		i(6, "Name"),
		t(" | "),
		i(7, "Init"),
		t(" | "),
		i(8, "Current/Max HP"),
		t(" | "),
		i(9, "Statuses"),
		t(" | "),
		i(10, "Notes"),
		t(" |"),
		t({ "", "| " }),
		i(11, "Name"),
		t(" | "),
		i(12, "Init"),
		t(" | "),
		i(13, "Current/Max HP"),
		t(" | "),
		i(14, "Statuses"),
		t(" | "),
		i(15, "Notes"),
		t(" |"),
	}),
})
